<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<!--<TargetFrameworks>;net8.0-ios</TargetFrameworks>-->
		<OutputType>Exe</OutputType>
		<RootNamespace>PokeRecipies</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>PokeRecipies</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>mx.zaraga.pokerecipies</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!--<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>-->
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\pokemon_recipies_icon.png" ForegroundFile="Resources\AppIcon\pokemon_recipies_icon.png" ForegroundScale="0.80" Color="#744ea5" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\sleep_recipes_icon.png" Color="#744ea5" BaseSize="256,256" Resize="True" />
		<!--<MauiSplashScreen Include="Resources\Splash\rs_splash.png" Color="#7753ab" BaseSize="1500,700" Resize="True"  />-->

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android'">
		<GoogleServicesJson Include="google-services.json" />
	</ItemGroup>

	<ItemGroup>
		<AndroidResource Remove="Views\**" />
		<Compile Remove="Views\**" />
		<EmbeddedResource Remove="Views\**" />
		<MauiCss Remove="Views\**" />
		<MauiXaml Remove="Views\**" />
		<None Remove="Views\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Google.Cloud.Firestore" Version="4.1.0" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.1" />
		<PackageReference Include="zaraga.logger" Version="1.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FirestoreCommunication\FirestoreCommunication.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Routes\Recipes\Recipe_detail\RecipePage.xaml.cs">
	    <DependentUpon>RecipePage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Routes\Recipes\Curry_list\CurryListPage.xaml.cs">
	    <DependentUpon>CurryListPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="Routes\Ingredients\Ingedient_detail\IngredientPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Routes\Ingredients\Ingredient_list\IngredientListPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Routes\Menu\MenuPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Routes\Recipes\Dessert_list\DessertListPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Routes\Recipes\Recipe_detail\RecipePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Routes\Recipes\Curry_list\CurryListPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Routes\Recipes\Salads_list\SaladsListPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Converter\" />
	</ItemGroup>

</Project>
